const token = location.pathname.split('/').filter(Boolean).at(-1); let definition;
const escape = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function input(q){const name=escape(q.key);if(q.type==='longText')return `<textarea name="${name}"></textarea>`;if(q.type==='singleSelect'||q.type==='multiSelect'||q.type==='yesNo'){const options=q.type==='yesNo'?['Yes','No']:q.options;const kind=q.type==='multiSelect'?'checkbox':'radio';return `<fieldset class="choices">${options.map(option=>`<label><input type="${kind}" name="${name}" value="${escape(option)}">${escape(option)}</label>`).join('')}</fieldset>`}if(q.type==='rating')return `<fieldset class="choices">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="${name}" value="${n}">${n} star${n>1?'s':''}</label>`).join('')}</fieldset>`;const type=q.type==='number'?'number':q.type==='date'?'date':'text';return `<input type="${type}" name="${name}">`}
function render(){document.title=`${definition.name} — Community Reach`;document.querySelector('#formTitle').textContent=definition.name;const questions=definition.sections.flatMap(s=>s.questions);document.querySelector('#progressText').textContent=`${questions.length} questions · About 4 minutes`;document.querySelector('#formContent').innerHTML=definition.sections.map(section=>`<section class="section"><h2>${escape(section.title)}</h2><p>${escape(section.description||'')}</p>${section.questions.map(q=>`<div class="question" data-key="${escape(q.key)}"${q.visibleWhen?` data-when-key="${escape(q.visibleWhen.fieldKey)}" data-when-value="${escape(q.visibleWhen.value)}"`:''}><label>${escape(q.label)} ${q.required?'<span class="required">*</span>':''}</label>${q.help?`<span class="help">${escape(q.help)}</span>`:''}${input(q)}<span class="field-error" hidden></span></div>`).join('')}</section>`).join('');document.querySelector('#loading').hidden=true;document.querySelector('#collectionForm').hidden=false;applyLogic()}
function answers(){const output={};definition.sections.flatMap(s=>s.questions).forEach(q=>{const entries=[...document.querySelectorAll(`[name="${CSS.escape(q.key)}"]`)];if(q.type==='multiSelect')output[q.key]=entries.filter(x=>x.checked).map(x=>x.value);else if(q.type==='singleSelect'||q.type==='yesNo'||q.type==='rating'){const selected=entries.find(x=>x.checked);if(selected)output[q.key]=q.type==='yesNo'?selected.value==='Yes':q.type==='rating'?Number(selected.value):selected.value}else if(entries[0]?.value)output[q.key]=q.type==='number'?Number(entries[0].value):entries[0].value});return output}
function applyLogic(){const current=answers();document.querySelectorAll('[data-when-key]').forEach(question=>{const actual=current[question.dataset.whenKey];const values=Array.isArray(actual)?actual:[actual];const visible=values.map(value=>String(value)).includes(question.dataset.whenValue);question.hidden=!visible;question.querySelectorAll('input,textarea,select').forEach(input=>input.disabled=!visible)})}
document.querySelector('#collectionForm').addEventListener('input',applyLogic);document.querySelector('#collectionForm').addEventListener('change',applyLogic);
document.querySelector('#collectionForm').onsubmit=async event=>{event.preventDefault();document.querySelectorAll('.field-error').forEach(el=>el.hidden=true);const error=document.querySelector('#formError');error.hidden=true;try{const response=await fetch(`/api/collect/${token}/submissions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:answers()})});const result=await response.json();if(!response.ok){if(result.fields)Object.entries(result.fields).forEach(([key,message])=>{const slot=document.querySelector(`[data-key="${CSS.escape(key)}"] .field-error`);if(slot){slot.textContent=message;slot.hidden=false}});throw new Error(result.error)}document.querySelector('#collectionForm').hidden=true;document.querySelector('#complete').hidden=false}catch(reason){error.textContent=reason.message;error.hidden=false;window.scrollTo({top:0,behavior:'smooth'})}};
fetch(`/api/collect/${token}`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);definition=result;render()}).catch(error=>{document.querySelector('#loading').textContent=error.message});
